CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE CLIENTE (
    idCliente INT PRIMARY KEY AUTO_INCREMENT,
    nomeCliente VARCHAR(100),
    cpf VARCHAR(14),
    rg VARCHAR(15),
    idEndereco INT
);

CREATE TABLE PRODUTO (
    idProduto INT PRIMARY KEY AUTO_INCREMENT,
    descricaoProduto VARCHAR(100)
);

CREATE TABLE VENDA (
    idVenda INT PRIMARY KEY AUTO_INCREMENT,
    dataVenda DATE,
    idCliente INT
);

CREATE TABLE CIDADE (
    idCidade INT PRIMARY KEY AUTO_INCREMENT,
    nomeCidade VARCHAR(100),
    idUF INT
);

CREATE TABLE UF (
    idUF INT PRIMARY KEY AUTO_INCREMENT,
    nomeUF VARCHAR(2),
	siglaUF VARCHAR(100)
);

CREATE TABLE ENDERECO (
    idEndereco INT PRIMARY KEY AUTO_INCREMENT,
    rua VARCHAR(100),
    numero INT,
    complemento VARCHAR(20),
    bairro VARCHAR(100),
    idCidade INT
);

CREATE TABLE ITEM_VENDA (
    idItemVenda INT PRIMARY KEY AUTO_INCREMENT,
    fk_VENDA_idVenda INT,
    fk_PRODUTO_idProduto INT,
    quantidae INT,
    precoUnitario FLOAT
);
 
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_2
    FOREIGN KEY (idEndereco)
    REFERENCES ENDERECO (idEndereco)
    ON DELETE RESTRICT;
 
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_2
    FOREIGN KEY (idCliente)
    REFERENCES CLIENTE (idCliente)
    ON DELETE RESTRICT;
 
ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_2
    FOREIGN KEY (idUF)
    REFERENCES UF (idUF)
    ON DELETE RESTRICT;
 
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_2
    FOREIGN KEY (idCidade)
    REFERENCES CIDADE (idCidade)
    ON DELETE RESTRICT;
 
ALTER TABLE ITEM_VENDA ADD CONSTRAINT FK_ITEM_VENDA_1
    FOREIGN KEY (fk_VENDA_idVenda)
    REFERENCES VENDA (idVenda)
    ON DELETE RESTRICT;
 
ALTER TABLE ITEM_VENDA ADD CONSTRAINT FK_ITEM_VENDA_2
    FOREIGN KEY (fk_PRODUTO_idProduto)
    REFERENCES PRODUTO (idProduto)
    ON DELETE RESTRICT;